In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('CAMDA-DILI/proccessed_data/LOOCV/result_loocv_mcnc.txt', delimiter=',', index_col=0)
df.head()

,similarities_all,similarities_DILI,similarities_noDILI,nn_DILI,nn_noDILI,true_label,predicted_label,correct,probability
0,[0.28313737172694065],[0.22426177406477885],[0.2766561351645191],2,3,1.0,[0.],[0],[[0.69333333 0.30666667]]
1,[0.20708603748012616],[0.19980576336331096],[0.20265779812892273],2,3,1.0,[1.],[1],[[0.43466667 0.56533333]]
2,[0.18513771618905275],[0.16339530799972707],[0.17499278865282086],1,4,1.0,[1.],[1],[[0.39066667 0.60933333]]
3,[0.20758724420431873],[0.20758724420431873],[0.1414585630862163],5,0,1.0,[1.],[1],[[0.24933333 0.75066667]]
4,[0.23255946967473623],[0.21694982610396746],[0.20912160508930758],2,3,1.0,[1.],[1],[[0.332 0.668]]

In [3]:
df.shape

(401, 9)

In [4]:
df['similarities_all'] = [i[1:-1] for i in df['similarities_all']]
df['similarities_DILI'] = [i[1:-1] for i in df['similarities_DILI']]
df['similarities_noDILI'] = [i[1:-1] for i in df['similarities_noDILI']]
df['predicted_label'] = [i[1:-1] for i in df['predicted_label']]

In [5]:
df['correct'] = [i[1:-1] for i in df['correct']]
df.head()

,similarities_all,similarities_DILI,similarities_noDILI,nn_DILI,nn_noDILI,true_label,predicted_label,correct,probability
0,0.28313737172694065,0.22426177406477885,0.2766561351645191,2,3,1.0,0.,0,[[0.69333333 0.30666667]]
1,0.20708603748012616,0.19980576336331096,0.20265779812892273,2,3,1.0,1.,1,[[0.43466667 0.56533333]]
2,0.18513771618905275,0.16339530799972707,0.17499278865282086,1,4,1.0,1.,1,[[0.39066667 0.60933333]]
3,0.20758724420431873,0.20758724420431873,0.1414585630862163,5,0,1.0,1.,1,[[0.24933333 0.75066667]]
4,0.23255946967473623,0.21694982610396746,0.20912160508930758,2,3,1.0,1.,1,[[0.332 0.668]]

In [6]:
df.index

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            391, 392, 393, 394, 395, 396, 397, 398, 399, 400],
           dtype='int64', length=401)

In [7]:
df = df.iloc[:,:-1]
df = df.astype(float)
df.dtypes

similarities_all       float64
similarities_DILI      float64
similarities_noDILI    float64
nn_DILI                float64
nn_noDILI              float64
true_label             float64
predicted_label        float64
correct                float64
dtype: object

In [8]:
df_result = pd.DataFrame()
df_result['bins'] = ['0-0.1','0.1-0.2','0.2-0.3','0.3-0.4','0.4-0.5','0.5-0.6','0.6-0.7','0.7-0.8','0.8-0.9','0.8-0.9']
df_result['counts_sim_all'] = [0 for i in range(10)]
df_result['correct_sim_all'] = [0 for i in range(10)]
df_result['accuracy_sim_all'] = [None for i in range(10)]
df_result['counts_sim_predicted_class'] = [0 for i in range(10)]
df_result['correct_sim_predicted_class'] = [0 for i in range(10)]
df_result['accuracy_sim_predicted_class'] = [None for i in range(10)]

In [9]:
for i,row in df.iterrows():
    for lim in [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]:
        if row['similarities_all'] <= (lim+0.1) and row['similarities_all'] > lim:
            df_result.iloc[int(lim*10),1] +=1
            if int(row['correct']) == 1:
                df_result.iloc[int(lim*10),2] +=1
        
        
        if row['predicted_label'] == 1:
            if row['similarities_DILI'] <= (lim+0.1) and row['similarities_DILI'] > lim:
                df_result.iloc[int(lim*10),4] +=1
                if row['correct'] == 1:
                    df_result.iloc[int(lim*10),5] +=1
        
        if row['predicted_label'] == 0:
            if row['similarities_noDILI'] <= (lim+0.1) and row['similarities_noDILI'] > lim:
                df_result.iloc[int(lim*10),4] +=1
                if int(row['correct']) == 1:
                    df_result.iloc[int(lim*10),5] +=1

In [10]:
df_result.head(10)

,bins,counts_sim_all,correct_sim_all,accuracy_sim_all,counts_sim_predicted_class,correct_sim_predicted_class,accuracy_sim_predicted_class
0,0-0.1,1,1,None,1,1,None
1,0.1-0.2,60,39,None,84,53,None
2,0.2-0.3,192,135,None,191,132,None
3,0.3-0.4,101,81,None,87,74,None
4,0.4-0.5,36,31,None,29,29,None
5,0.5-0.6,11,11,None,9,9,None
6,0.6-0.7,0,0,None,0,0,None
7,0.7-0.8,0,0,None,0,0,None
8,0.8-0.9,0,0,None,0,0,None
9,0.8-0.9,0,0,None,0,0,None

In [11]:
for i,row in df_result.iterrows():
    if row['counts_sim_all'] > 0:
        df_result.iloc[i,3] = (row['correct_sim_all']/row['counts_sim_all'])
    if row['counts_sim_predicted_class'] > 0:
        df_result.iloc[i,6] = (row['correct_sim_predicted_class']/row['counts_sim_predicted_class'])

In [12]:
df_result.head(10)

,bins,counts_sim_all,correct_sim_all,accuracy_sim_all,counts_sim_predicted_class,correct_sim_predicted_class,accuracy_sim_predicted_class
0,0-0.1,1,1,1,1,1,1
1,0.1-0.2,60,39,0.65,84,53,0.630952
2,0.2-0.3,192,135,0.703125,191,132,0.691099
3,0.3-0.4,101,81,0.80198,87,74,0.850575
4,0.4-0.5,36,31,0.861111,29,29,1
5,0.5-0.6,11,11,1,9,9,1
6,0.6-0.7,0,0,None,0,0,None
7,0.7-0.8,0,0,None,0,0,None
8,0.8-0.9,0,0,None,0,0,None
9,0.8-0.9,0,0,None,0,0,None

In [13]:
df_result.to_csv('CAMDA-DILI/proccessed_data/LOOCV/loocv_mcnc_results.csv', sep=',', index=False)

# Prediction ambiguous

In [14]:
predictions = pd.read_csv('CAMDA-DILI/proccessed_data/LOOCV//ecfp_rf_mcnc.csv', delimiter=',', index_col=0)
predictions.head()

  Compound.Name Predicted.Label
0    amantadine          NoDILI
1    anagrelide            DILI
2    bumetanide            DILI
3     diazoxide            DILI
4  dipyridamole          NoDILI

# Import Similarities

In [15]:
tani = pd.read_csv('CAMDA-DILI/proccessed_data/Standardization/tanimoto_similarities.txt', delimiter=',', header=None)
tani.columns = ['C1', 'C2', 'Tanimoto']
tani = tani.pivot(index='C1', columns='C2', values='Tanimoto')

tani_mcnc = pd.concat([tani.iloc[:174,:174],tani.iloc[:174,434:661]],axis=1)
tani_mcnc = pd.concat([tani_mcnc,pd.concat([tani.iloc[434:661,:174],tani.iloc[434:661,434:661]],axis=1)],axis=0)

d = {}
for i,j in enumerate(tani_mcnc.columns.values):
    d[j] = i

tani_mcnc = tani_mcnc.rename(d,axis=1)
tani_mcnc = tani_mcnc.rename(d,axis=0)    


tani_all = pd.read_csv('CAMDA-DILI/proccessed_data/Standardization/tanimoto_similarities.txt', delimiter=',', header=None)
tani_all.columns = ['C1', 'C2', 'Tanimoto']
tani_all = tani_all.pivot(index='C1', columns='C2', values='Tanimoto')

In [16]:
tani_mcnc.head()

C2,0,1,2,3,4,5,6,7,8,9,...,391,392,393,394,395,396,397,398,399,400
C1,,,,,,,,,,,,,,,,,,,,,
0,1.000000,0.116667,0.082192,0.126582,0.140625,0.109756,0.113924,0.114754,0.108696,0.169492,...,0.121212,0.177419,0.104167,0.085470,0.056180,0.110169,0.090909,0.084507,0.319149,0.102564
1,0.116667,1.000000,0.151515,0.061728,0.093750,0.113924,0.118421,0.203704,0.112360,0.100000,...,0.092308,0.093750,0.111111,0.097345,0.070588,0.103448,0.096154,0.057143,0.092593,0.077922
2,0.082192,0.151515,1.000000,0.076923,0.108108,0.086957,0.077778,0.069444,0.077670,0.068493,...,0.169014,0.078947,0.050847,0.062500,0.030000,0.085271,0.061538,0.048780,0.092308,0.117647
3,0.126582,0.061728,0.076923,1.000000,0.108434,0.067961,0.080808,0.087500,0.080357,0.100000,...,0.134146,0.069767,0.090909,0.073529,0.018018,0.071429,0.053333,0.032258,0.125000,0.071429
4,0.140625,0.093750,0.108108,0.108434,1.000000,0.093023,0.070588,0.092308,0.082474,0.125000,...,0.084507,0.117647,0.056604,0.056911,0.043011,0.089431,0.050000,0.038961,0.140351,0.085366

In [17]:
tani_all.head()

C2,1,2,3,4,5,6,7,8,9,10,...,966,967,968,969,970,971,972,973,974,975
C1,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.116667,0.082192,0.126582,0.140625,0.109756,0.113924,0.114754,0.108696,0.169492,...,0.142857,0.097561,0.097222,0.172414,0.117647,0.112676,0.065217,0.117647,0.100000,0.093333
2,0.116667,1.000000,0.151515,0.061728,0.093750,0.113924,0.118421,0.203704,0.112360,0.100000,...,0.089286,0.175676,0.070423,0.083333,0.106061,0.070423,0.091954,0.047170,0.093220,0.112676
3,0.082192,0.151515,1.000000,0.076923,0.108108,0.086957,0.077778,0.069444,0.077670,0.068493,...,0.073529,0.125000,0.086420,0.069444,0.062500,0.073171,0.103093,0.042373,0.076336,0.083333
4,0.126582,0.061728,0.076923,1.000000,0.108434,0.067961,0.080808,0.087500,0.080357,0.100000,...,0.136986,0.048077,0.076923,0.175676,0.055556,0.076923,0.125000,0.090164,0.070922,0.052083
5,0.140625,0.093750,0.108108,0.108434,1.000000,0.093023,0.070588,0.092308,0.082474,0.125000,...,0.175439,0.094118,0.064935,0.163934,0.128571,0.138889,0.122222,0.103774,0.088710,0.075949

In [18]:
tani_mcrows = pd.concat([tani_all.iloc[:174,:174],tani_all.iloc[:174,434:661],tani_all.iloc[:174,920:]],axis=1)
tani_ncrows = pd.concat([tani_all.iloc[434:661,:174],tani_all.iloc[434:661,434:661],tani_all.iloc[434:661,920:]],axis=1)
tani_ambirows = pd.concat([tani_all.iloc[920:,:174],tani_all.iloc[920:,434:661],tani_all.iloc[920:,920:]],axis=1)

In [19]:
tani_mcncambi = pd.concat([tani_mcrows,tani_ncrows,tani_ambirows],axis=0)

In [20]:
tani_mcncambi.shape

(456, 456)

In [21]:
#reset indices
d = {}
for i,j in enumerate(tani_mcncambi.columns.values):
    d[j] = i
tani_mcncambi = tani_mcncambi.rename(d,axis=1)
tani_mcncambi = tani_mcncambi.rename(d,axis=0)  
tani_mcncambi.head()

C2,0,1,2,3,4,5,6,7,8,9,...,446,447,448,449,450,451,452,453,454,455
C1,,,,,,,,,,,,,,,,,,,,,
0,1.000000,0.116667,0.082192,0.126582,0.140625,0.109756,0.113924,0.114754,0.108696,0.169492,...,0.142857,0.097561,0.097222,0.172414,0.117647,0.112676,0.065217,0.117647,0.100000,0.093333
1,0.116667,1.000000,0.151515,0.061728,0.093750,0.113924,0.118421,0.203704,0.112360,0.100000,...,0.089286,0.175676,0.070423,0.083333,0.106061,0.070423,0.091954,0.047170,0.093220,0.112676
2,0.082192,0.151515,1.000000,0.076923,0.108108,0.086957,0.077778,0.069444,0.077670,0.068493,...,0.073529,0.125000,0.086420,0.069444,0.062500,0.073171,0.103093,0.042373,0.076336,0.083333
3,0.126582,0.061728,0.076923,1.000000,0.108434,0.067961,0.080808,0.087500,0.080357,0.100000,...,0.136986,0.048077,0.076923,0.175676,0.055556,0.076923,0.125000,0.090164,0.070922,0.052083
4,0.140625,0.093750,0.108108,0.108434,1.000000,0.093023,0.070588,0.092308,0.082474,0.125000,...,0.175439,0.094118,0.064935,0.163934,0.128571,0.138889,0.122222,0.103774,0.088710,0.075949

In [22]:
#for each of the ambiguous compute: i) similarity all (0-400) ii) similarity predicted class (0-173/174-400)
sims_all = []
sims_pre_class = []

import numpy as np
#function that gathers similarities for each compound of a group to compounds of another group (inter)
def five_nn_sim_dg(df, idx_compounds_a, idx_compounds_b):
    
    
    #consider only columns of idx_compounds_b for comparison
    df = df[idx_compounds_b]
    
    for i,row in df.iterrows():
        #consider only rows within idx_compounds_a
        if i != idx_compounds_a:
            continue
        l = list(row)
        l.sort(reverse=True)
    return(np.mean(l[0:5]))

labels = []

for i,label in enumerate(predictions['Predicted.Label']):
    sims_all.append(five_nn_sim_dg(tani_mcncambi,i+401,list(range(401))))
    labels.append(label)
    
    if label=='DILI':
        sims_pre_class.append(five_nn_sim_dg(tani_mcncambi,i+401,list(range(174))))
    
    if label=='NoDILI':
        sims_pre_class.append(five_nn_sim_dg(tani_mcncambi,i+401,list(range(174,401))))
                              
df_ambi_sim = pd.DataFrame()
df_ambi_sim['similarities_all'] = sims_all
df_ambi_sim['similarities_predicted_class'] = sims_pre_class
df_ambi_sim['Predicted.Label'] = labels
                              
df_ambi_sim.head()

   similarities_all  similarities_predicted_class Predicted.Label
0          0.188031                      0.185184          NoDILI
1          0.187248                      0.185966            DILI
2          0.262568                      0.262568            DILI
3          0.245078                      0.245078            DILI
4          0.187907                      0.187907          NoDILI

In [23]:
df_ambi_sim

    similarities_all  similarities_predicted_class Predicted.Label
0           0.188031                      0.185184          NoDILI
1           0.187248                      0.185966            DILI
2           0.262568                      0.262568            DILI
3           0.245078                      0.245078            DILI
4           0.187907                      0.187907          NoDILI
5           0.301380                      0.258104          NoDILI
6           0.328039                      0.328039          NoDILI
7           0.322360                      0.317521            DILI
8           0.314595                      0.295619            DILI
9           0.656886                      0.656886          NoDILI
10          0.288060                      0.271802            DILI
11          0.229028                      0.217921          NoDILI
12          0.241255                      0.230091            DILI
13          0.398600                      0.335173            DILI
14          0.391287                      0.389678            DILI
15          0.251253                      0.233186            DILI
16          0.197613                      0.192355          NoDILI
17          0.362312                      0.362312          NoDILI
18          0.375910                      0.375910          NoDILI
19          0.233213                      0.204111            DILI
20          0.192931                      0.183447          NoDILI
21          0.330154                      0.306883            DILI
22          0.352801                      0.336665            DILI
23          0.330810                      0.323236          NoDILI
24          0.202805                      0.188867          NoDILI
25          0.284380                      0.272652          NoDILI
26          0.306149                      0.305565            DILI
27          0.143494                      0.135364          NoDILI
28          0.207803                      0.205363          NoDILI
29          0.257024                      0.213753          NoDILI
30          0.257988                      0.251107            DILI
31          0.299839                      0.281382          NoDILI
32          0.261052                      0.234582          NoDILI
33          0.308614                      0.268889            DILI
34          0.439001                      0.405952          NoDILI
35          0.204380                      0.187547            DILI
36          0.205570                      0.197371            DILI
37          0.248080                      0.243462          NoDILI
38          0.355394                      0.355394          NoDILI
39          0.307553                      0.306312          NoDILI
40          0.237674                      0.230078          NoDILI
41          0.321030                      0.321030          NoDILI
42          0.288704                      0.283891          NoDILI
43          0.220129                      0.209094          NoDILI
44          0.293736                      0.275895          NoDILI
45          0.258826                      0.249166            DILI
46          0.193293                      0.180966            DILI
47          0.246208                      0.246208          NoDILI
48          0.255122                      0.252092            DILI
49          0.246702                      0.235395          NoDILI
50          0.310138                      0.275566            DILI
51          0.186606                      0.175316            DILI
52          0.164259                      0.160877          NoDILI
53          0.300343                      0.295916          NoDILI
54          0.315362                      0.304181          NoDILI

In [24]:
df_ambi_dist = pd.DataFrame()
df_ambi_dist['bins'] = ['0-0.1','0.1-0.2','0.2-0.3','0.3-0.4','0.4-0.5','0.5-0.6','0.6-0.7','0.7-0.8','0.8-0.9','0.8-0.9']
df_ambi_dist['counts_sim_all'] = [0 for i in range(10)]
df_ambi_dist['counts_sim_predicted_class'] = [0 for i in range(10)]



for i,row in df_ambi_sim.iterrows():
    for lim in [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]:
        
        if row['similarities_all'] <= (lim+0.1) and row['similarities_all'] > lim:
            df_ambi_dist.iloc[int(lim*10),1] +=1
            
        if row['similarities_predicted_class'] <= (lim+0.1) and row['similarities_predicted_class'] > lim:
            df_ambi_dist.iloc[int(lim*10),2] +=1

In [25]:
df_ambi_dist.to_csv('CAMDA-DILI/proccessed_data/LOOCV/similarity_ambi_mcnc.csv', sep=',', index=False)

In [26]:
df_ambi_dist.head()

      bins  counts_sim_all  counts_sim_predicted_class
0    0-0.1               0                           0
1  0.1-0.2               9                          12
2  0.2-0.3              25                          27
3  0.3-0.4              19                          14
4  0.4-0.5               1                           1